name: compscore-to
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pytorch=2.6.0
  - pytorch-cuda=12.4
  - numpy=2.2.3
  - scipy=1.15.2
  - pip
  - pip:
      - nibabel==5.3.2
      - pydicom==3.0.1
      - omegaconf==2.3.0
      - h5py==3.13.0

